#!/usr/bin/env node

var Hook = require('hook.io').Hook;
var jsdom = new Hook( { name: "jsdom"} );
var jsdomModule  = require("jsdom");

jsdom.start();

jsdom.on('i.build.o.build', function(event, data){
  
 var window = jsdomModule.jsdom().createWindow();
 jsdomModule.jQueryify(window, "http://code.jquery.com/jquery-1.4.2.js", function(){
   window.jQuery('body').append(data);
   jsdom.emit('o.buildResponse', window.jQuery(".testing").text());
 });
 
});


jsdom.on('ready', function(){
  
  jsdom.emit('o.build', "<div class='testing'>Hello World, It works!</div>")
  
});